name: prow-github

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  prow:
    runs-on: ubuntu-latest
    steps:
      - name: Prow essential commands
        uses: jpmcb/prow-github-actions@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          prow-commands: >
            /lgtm
            /approve
            /hold
            /hold cancel
            /automerge
