name: prow-automerge

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  prow:
    runs-on: ubuntu-latest
    steps:
      - name: Run Prow Commands
        uses: jpmcb/prow-github-actions@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          prow-commands: "/lgtm /approve /hold /hold-cancel automerge remove-lgtm"
