name: prow-remove-lgtm

on:
  pull_request:
    types: [synchronize]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  remove-lgtm:
    runs-on: ubuntu-latest
    steps:
      - name: Remove LGTM on update
        uses: jpmcb/prow-github-actions@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          prow-commands: remove-lgtm
